export const categories = [
  "Housing",
  "Transportation",
  "Food",
  "Healthcare",
  "Entertainment",
  "Travel",
  "Clothing",
  "Personal Care",
  "Education",
  "Gifts and Donations",
  "Debts and Loans",
  "Savings and Investments",
  "Utilities",
  "Childcare",
  "Insurance",
  "Taxes",
  "Miscellaneous",
];
